/* Used Car Deal Analyzer — baked dataset (Appendix B schema).
 *
 * This block is REGENERATED by build_datasets.py. Values between the
 * DATA-START / DATA-END markers are machine-managed; edit the script, not this file.
 *
 * The `meta.sources` stamps say where each table came from and when. A table sourced
 * as "curated" is a hand-maintained transcription of published figures (cited in
 * README.md § Data sources) — it is the offline baseline. Running
 * `python3 build_datasets.py --refresh` on a machine with network access replaces
 * the fitted tables (vehicles, depCurves, mileSlopes, complaints, recallCounts)
 * with values derived from EPA / NHTSA / listing-corpus data.
 */
/* ==DATA-START== */
(function (root, factory) {
  var data = factory();
  if (typeof module === 'object' && module.exports) module.exports = data;
  else root.UCDA_DATA = data;
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  return {
    meta: {
      built: '2026-08-05',
      schema: 1,
      sources: {
        vehicles: 'curated (EPA fueleconomy.gov vehicles.csv subset, MY2010-2024)',
        brands: 'curated (RepairPal maintenance cost; Consumer Reports / JD Power reliability; iSeeCars longevity)',
        segments: 'curated (Bankrate/NerdWallet full-coverage premium averages; EPA class MPG)',
        depCurves: 'curated (iSeeCars 5-year depreciation by segment, converted to annual piecewise rates)',
        mileSlopes: 'curated (industry mileage-adjustment convention, banded by price)',
        complaints: 'curated (NHTSA ODI complaint volumes, representative model-years)',
        recallCounts: 'curated (NHTSA recall campaign counts, representative model-years)',
        aprByTier: 'curated (Experian State of the Automotive Finance Market, used-vehicle averages)',
        energy: 'curated (EIA weekly retail gasoline; EIA residential electricity average)'
      },
      // Tables older than this many months trigger a warning from `build_datasets.py --check`
      staleAfterMonths: 12
    },

    /* Brand-level maintenance cost, reliability baseline and expected service life.
     * maintPerYear: average annual maintenance + repair spend, USD
     * relBaseline:  composite reliability 0-100
     * lifeMiles:    typical useful life before major-repair economics dominate */
    brands: {
      'Toyota':        { maintPerYear: 441,  relBaseline: 90, lifeMiles: 250000 },
      'Lexus':         { maintPerYear: 551,  relBaseline: 92, lifeMiles: 250000 },
      'Honda':         { maintPerYear: 428,  relBaseline: 84, lifeMiles: 230000 },
      'Acura':         { maintPerYear: 501,  relBaseline: 80, lifeMiles: 220000 },
      'Mazda':         { maintPerYear: 462,  relBaseline: 86, lifeMiles: 220000 },
      'Subaru':        { maintPerYear: 617,  relBaseline: 79, lifeMiles: 220000 },
      'Hyundai':       { maintPerYear: 468,  relBaseline: 77, lifeMiles: 200000 },
      'Kia':           { maintPerYear: 474,  relBaseline: 78, lifeMiles: 200000 },
      'Nissan':        { maintPerYear: 500,  relBaseline: 70, lifeMiles: 200000 },
      'Infiniti':      { maintPerYear: 638,  relBaseline: 64, lifeMiles: 200000 },
      'Mitsubishi':    { maintPerYear: 535,  relBaseline: 68, lifeMiles: 190000 },
      'Ford':          { maintPerYear: 775,  relBaseline: 62, lifeMiles: 200000 },
      'Chevrolet':     { maintPerYear: 649,  relBaseline: 64, lifeMiles: 200000 },
      'GMC':           { maintPerYear: 744,  relBaseline: 62, lifeMiles: 200000 },
      'Buick':         { maintPerYear: 608,  relBaseline: 72, lifeMiles: 200000 },
      'Cadillac':      { maintPerYear: 783,  relBaseline: 54, lifeMiles: 190000 },
      'Ram':           { maintPerYear: 858,  relBaseline: 58, lifeMiles: 200000 },
      'Dodge':         { maintPerYear: 634,  relBaseline: 60, lifeMiles: 190000 },
      'Jeep':          { maintPerYear: 634,  relBaseline: 52, lifeMiles: 180000 },
      'Chrysler':      { maintPerYear: 608,  relBaseline: 56, lifeMiles: 180000 },
      'Volkswagen':    { maintPerYear: 676,  relBaseline: 60, lifeMiles: 180000 },
      'Audi':          { maintPerYear: 987,  relBaseline: 62, lifeMiles: 180000 },
      'BMW':           { maintPerYear: 968,  relBaseline: 66, lifeMiles: 180000 },
      'Mercedes-Benz': { maintPerYear: 908,  relBaseline: 58, lifeMiles: 190000 },
      'Volvo':         { maintPerYear: 769,  relBaseline: 56, lifeMiles: 200000 },
      'Mini':          { maintPerYear: 846,  relBaseline: 62, lifeMiles: 170000 },
      'Porsche':       { maintPerYear: 1192, relBaseline: 78, lifeMiles: 200000 },
      'Land Rover':    { maintPerYear: 1174, relBaseline: 40, lifeMiles: 150000 },
      'Lincoln':       { maintPerYear: 879,  relBaseline: 60, lifeMiles: 190000 },
      'Tesla':         { maintPerYear: 587,  relBaseline: 56, lifeMiles: 250000 },
      'Other':         { maintPerYear: 652,  relBaseline: 65, lifeMiles: 200000 }
    },

    /* Segment defaults. mpg/insPerYear are fallbacks when no per-model record exists.
     * evKwhPer100mi is set for electric segments (fuel math switches to electricity). */
    segments: {
      'Compact car':     { mpg: 32, insPerYear: 1700 },
      'Midsize car':     { mpg: 30, insPerYear: 1750 },
      'Compact SUV':     { mpg: 28, insPerYear: 1650 },
      'Midsize SUV':     { mpg: 22, insPerYear: 1800 },
      'Pickup truck':    { mpg: 20, insPerYear: 1850 },
      'Minivan':         { mpg: 24, insPerYear: 1700 },
      'Sports car':      { mpg: 24, insPerYear: 2300 },
      'Luxury':          { mpg: 24, insPerYear: 2200 },
      'Hybrid':          { mpg: 45, insPerYear: 1750 },
      'Electric':        { mpg: 0,  insPerYear: 1950, evKwhPer100mi: 33 }
    },

    /* Piecewise annual depreciation rates by segment (fraction of current value per year),
     * with knots at ages 5, 8 and 12 — the observed old-car slowdown.
     * brandAdj shifts the rate additively (clamped +/-0.03 by the engine). */
    depCurves: {
      'Compact car':  { r1_5: 0.145, r6_8: 0.117, r9_12: 0.088, r13p: 0.065 },
      'Midsize car':  { r1_5: 0.155, r6_8: 0.126, r9_12: 0.095, r13p: 0.070 },
      'Compact SUV':  { r1_5: 0.145, r6_8: 0.117, r9_12: 0.088, r13p: 0.065 },
      'Midsize SUV':  { r1_5: 0.165, r6_8: 0.134, r9_12: 0.101, r13p: 0.074 },
      'Pickup truck': { r1_5: 0.125, r6_8: 0.101, r9_12: 0.076, r13p: 0.056 },
      'Minivan':      { r1_5: 0.175, r6_8: 0.142, r9_12: 0.107, r13p: 0.079 },
      'Sports car':   { r1_5: 0.165, r6_8: 0.134, r9_12: 0.101, r13p: 0.074 },
      'Luxury':       { r1_5: 0.195, r6_8: 0.158, r9_12: 0.119, r13p: 0.088 },
      'Hybrid':       { r1_5: 0.145, r6_8: 0.117, r9_12: 0.088, r13p: 0.065 },
      'Electric':     { r1_5: 0.185, r6_8: 0.150, r9_12: 0.113, r13p: 0.083 },
      brandAdj: {
        'Toyota': -0.013, 'Lexus': -0.010, 'Honda': -0.011, 'Subaru': -0.009,
        'Mazda': -0.006, 'Porsche': -0.012, 'Tesla': 0.010, 'Jeep': 0.006,
        'Nissan': 0.008, 'Chrysler': 0.012, 'Cadillac': 0.014, 'Lincoln': 0.014,
        'Infiniti': 0.013, 'Land Rover': 0.024, 'BMW': 0.018, 'Mercedes-Benz': 0.018,
        'Audi': 0.016, 'Volvo': 0.013, 'Mini': 0.011
      }
    },

    /* Dollar-per-mile adjustment when odometer deviates from the age-expected mileage,
     * banded by vehicle price. Engine clamps to [0.02, 0.25]. */
    mileSlopes: {
      'default': [
        { maxPrice: 8000,   usdPerMile: 0.035 },
        { maxPrice: 15000,  usdPerMile: 0.060 },
        { maxPrice: 25000,  usdPerMile: 0.090 },
        { maxPrice: 40000,  usdPerMile: 0.130 },
        { maxPrice: 999999, usdPerMile: 0.180 }
      ],
      'Pickup truck': [
        { maxPrice: 15000,  usdPerMile: 0.050 },
        { maxPrice: 30000,  usdPerMile: 0.080 },
        { maxPrice: 999999, usdPerMile: 0.120 }
      ],
      'Luxury': [
        { maxPrice: 15000,  usdPerMile: 0.080 },
        { maxPrice: 30000,  usdPerMile: 0.140 },
        { maxPrice: 999999, usdPerMile: 0.200 }
      ]
    },

    /* Per-model EPA figures + segment mapping. Keyed make -> model -> year.
     * `build_datasets.py --refresh` expands this from the full EPA vehicles.csv. */
    vehicles: {
      'Toyota': {
        'Camry':     { seg: 'Midsize car', years: { 2015: 28, 2017: 29, 2019: 32, 2021: 32, 2023: 32 } },
        'Corolla':   { seg: 'Compact car', years: { 2015: 31, 2017: 32, 2019: 34, 2021: 35, 2023: 35 } },
        'RAV4':      { seg: 'Compact SUV', years: { 2015: 26, 2017: 26, 2019: 30, 2021: 30, 2023: 30 } },
        'Highlander':{ seg: 'Midsize SUV', years: { 2015: 21, 2017: 22, 2019: 23, 2021: 24, 2023: 24 } },
        'Tacoma':    { seg: 'Pickup truck', years: { 2015: 21, 2017: 21, 2019: 21, 2021: 21, 2023: 21 } },
        'Tundra':    { seg: 'Pickup truck', years: { 2015: 15, 2017: 15, 2019: 15, 2021: 15, 2023: 20 } },
        'Sienna':    { seg: 'Minivan', years: { 2015: 21, 2017: 21, 2019: 22, 2021: 36, 2023: 36 } },
        'Prius':     { seg: 'Hybrid', years: { 2015: 50, 2017: 52, 2019: 52, 2021: 52, 2023: 57 } }
      },
      'Honda': {
        'Civic':     { seg: 'Compact car', years: { 2015: 33, 2017: 35, 2019: 36, 2021: 36, 2023: 35 } },
        'Accord':    { seg: 'Midsize car', years: { 2015: 31, 2017: 31, 2019: 33, 2021: 33, 2023: 32 } },
        'CR-V':      { seg: 'Compact SUV', years: { 2015: 29, 2017: 30, 2019: 30, 2021: 30, 2023: 30 } },
        'Pilot':     { seg: 'Midsize SUV', years: { 2015: 21, 2017: 22, 2019: 22, 2021: 22, 2023: 22 } },
        'Odyssey':   { seg: 'Minivan', years: { 2015: 22, 2017: 22, 2019: 22, 2021: 22, 2023: 22 } }
      },
      'Ford': {
        'F-150':     { seg: 'Pickup truck', years: { 2015: 19, 2017: 20, 2019: 21, 2021: 22, 2023: 22 } },
        'Escape':    { seg: 'Compact SUV', years: { 2015: 25, 2017: 26, 2019: 26, 2021: 30, 2023: 30 } },
        'Explorer':  { seg: 'Midsize SUV', years: { 2015: 20, 2017: 20, 2019: 21, 2021: 24, 2023: 24 } },
        'Fusion':    { seg: 'Midsize car', years: { 2015: 26, 2017: 26, 2019: 27, 2021: 27 } },
        'Mustang':   { seg: 'Sports car', years: { 2015: 20, 2017: 21, 2019: 21, 2021: 22, 2023: 22 } }
      },
      'Chevrolet': {
        'Silverado 1500': { seg: 'Pickup truck', years: { 2015: 18, 2017: 19, 2019: 19, 2021: 20, 2023: 20 } },
        'Equinox':   { seg: 'Compact SUV', years: { 2015: 24, 2017: 26, 2019: 28, 2021: 28, 2023: 28 } },
        'Malibu':    { seg: 'Midsize car', years: { 2015: 29, 2017: 32, 2019: 32, 2021: 32, 2023: 32 } },
        'Tahoe':     { seg: 'Midsize SUV', years: { 2015: 18, 2017: 18, 2019: 18, 2021: 18, 2023: 18 } },
        'Bolt EV':   { seg: 'Electric', years: { 2017: 0, 2019: 0, 2021: 0, 2023: 0 }, kwhPer100mi: 28 }
      },
      'Nissan': {
        'Altima':    { seg: 'Midsize car', years: { 2015: 31, 2017: 31, 2019: 32, 2021: 32, 2023: 32 } },
        'Rogue':     { seg: 'Compact SUV', years: { 2015: 28, 2017: 29, 2019: 29, 2021: 30, 2023: 33 } },
        'Sentra':    { seg: 'Compact car', years: { 2015: 33, 2017: 32, 2019: 32, 2021: 33, 2023: 33 } },
        'Leaf':      { seg: 'Electric', years: { 2015: 0, 2017: 0, 2019: 0, 2021: 0, 2023: 0 }, kwhPer100mi: 30 }
      },
      'Subaru': {
        'Outback':   { seg: 'Compact SUV', years: { 2015: 28, 2017: 28, 2019: 29, 2021: 29, 2023: 29 } },
        'Forester':  { seg: 'Compact SUV', years: { 2015: 28, 2017: 28, 2019: 29, 2021: 29, 2023: 29 } },
        'Impreza':   { seg: 'Compact car', years: { 2015: 31, 2017: 31, 2019: 31, 2021: 31, 2023: 31 } },
        'Crosstrek': { seg: 'Compact SUV', years: { 2017: 29, 2019: 30, 2021: 30, 2023: 29 } }
      },
      'Tesla': {
        'Model 3':   { seg: 'Electric', years: { 2019: 0, 2021: 0, 2023: 0 }, kwhPer100mi: 25 },
        'Model Y':   { seg: 'Electric', years: { 2021: 0, 2023: 0 }, kwhPer100mi: 28 },
        'Model S':   { seg: 'Electric', years: { 2015: 0, 2017: 0, 2019: 0, 2021: 0 }, kwhPer100mi: 33 }
      },
      'Jeep': {
        'Grand Cherokee': { seg: 'Midsize SUV', years: { 2015: 21, 2017: 21, 2019: 21, 2021: 22, 2023: 22 } },
        'Wrangler':  { seg: 'Midsize SUV', years: { 2015: 19, 2017: 19, 2019: 21, 2021: 22, 2023: 22 } },
        'Cherokee':  { seg: 'Compact SUV', years: { 2015: 24, 2017: 24, 2019: 25, 2021: 25, 2023: 25 } }
      },
      'BMW': {
        '3 Series':  { seg: 'Luxury', years: { 2015: 27, 2017: 28, 2019: 30, 2021: 30, 2023: 30 } },
        '5 Series':  { seg: 'Luxury', years: { 2015: 26, 2017: 27, 2019: 28, 2021: 28, 2023: 28 } },
        'X3':        { seg: 'Luxury', years: { 2015: 24, 2017: 25, 2019: 26, 2021: 26, 2023: 26 } },
        'X5':        { seg: 'Luxury', years: { 2015: 21, 2017: 22, 2019: 23, 2021: 24, 2023: 24 } }
      },
      'Hyundai': {
        'Elantra':   { seg: 'Compact car', years: { 2015: 32, 2017: 32, 2019: 35, 2021: 37, 2023: 37 } },
        'Sonata':    { seg: 'Midsize car', years: { 2015: 29, 2017: 30, 2019: 31, 2021: 32, 2023: 32 } },
        'Tucson':    { seg: 'Compact SUV', years: { 2015: 25, 2017: 26, 2019: 26, 2021: 26, 2023: 28 } },
        'Santa Fe':  { seg: 'Midsize SUV', years: { 2015: 21, 2017: 22, 2019: 25, 2021: 25, 2023: 25 } }
      },
      'Kia': {
        'Optima':    { seg: 'Midsize car', years: { 2015: 27, 2017: 29, 2019: 31, 2021: 31 } },
        'Soul':      { seg: 'Compact car', years: { 2015: 27, 2017: 28, 2019: 29, 2021: 30, 2023: 30 } },
        'Sorento':   { seg: 'Midsize SUV', years: { 2015: 21, 2017: 22, 2019: 22, 2021: 24, 2023: 24 } },
        'Telluride': { seg: 'Midsize SUV', years: { 2020: 23, 2021: 23, 2023: 23 } }
      },
      'Mazda': {
        'Mazda3':    { seg: 'Compact car', years: { 2015: 33, 2017: 32, 2019: 30, 2021: 30, 2023: 30 } },
        'CX-5':      { seg: 'Compact SUV', years: { 2015: 28, 2017: 27, 2019: 28, 2021: 28, 2023: 28 } },
        'Mazda6':    { seg: 'Midsize car', years: { 2015: 30, 2017: 30, 2019: 29, 2021: 29 } }
      }
    },

    /* NHTSA ODI complaint volumes for representative model-years.
     * Key: "MAKE|MODEL|YEAR". `per100k` is the normalized rate used by the score;
     * `segP90` is the 90th-percentile rate within the segment (the score's scale anchor). */
    complaints: {
      'TOYOTA|CAMRY|2019':      { count: 61,  per100k: 14.2, top: ['ELECTRICAL SYSTEM', 'POWERTRAIN'] },
      'TOYOTA|COROLLA|2019':    { count: 44,  per100k: 11.8, top: ['ELECTRICAL SYSTEM'] },
      'TOYOTA|RAV4|2019':       { count: 214, per100k: 38.4, top: ['POWERTRAIN', 'FUEL SYSTEM'] },
      'HONDA|CIVIC|2019':       { count: 132, per100k: 27.1, top: ['ELECTRICAL SYSTEM', 'STRUCTURE'] },
      'HONDA|ACCORD|2019':      { count: 178, per100k: 41.3, top: ['ELECTRICAL SYSTEM', 'ENGINE'] },
      'HONDA|CR-V|2019':        { count: 246, per100k: 46.9, top: ['ENGINE', 'FUEL SYSTEM'] },
      'FORD|F-150|2019':        { count: 389, per100k: 52.7, top: ['POWERTRAIN', 'ELECTRICAL SYSTEM'] },
      'FORD|EXPLORER|2020':     { count: 612, per100k: 98.4, top: ['POWERTRAIN', 'STRUCTURE', 'ELECTRICAL SYSTEM'] },
      'CHEVROLET|EQUINOX|2018': { count: 421, per100k: 76.2, top: ['ENGINE', 'POWERTRAIN'] },
      'NISSAN|ROGUE|2018':      { count: 358, per100k: 64.5, top: ['POWERTRAIN', 'FORWARD COLLISION AVOIDANCE'] },
      'NISSAN|ALTIMA|2019':     { count: 197, per100k: 48.2, top: ['POWERTRAIN'] },
      'JEEP|GRAND CHEROKEE|2019': { count: 288, per100k: 71.3, top: ['ELECTRICAL SYSTEM', 'POWERTRAIN'] },
      'SUBARU|OUTBACK|2020':    { count: 341, per100k: 69.8, top: ['ELECTRICAL SYSTEM', 'VISIBILITY'] },
      'TESLA|MODEL 3|2019':     { count: 156, per100k: 33.6, top: ['STRUCTURE', 'ELECTRICAL SYSTEM'] }
    },

    /* Segment 90th-percentile complaint rates — the denominator for the reliability blend. */
    complaintSegP90: {
      'Compact car': 60, 'Midsize car': 70, 'Compact SUV': 75, 'Midsize SUV': 95,
      'Pickup truck': 85, 'Minivan': 80, 'Sports car': 55, 'Luxury': 65,
      'Hybrid': 55, 'Electric': 60, 'default': 70
    },

    /* Offline fallback for open-recall counts (live NHTSA API supersedes when reachable). */
    recallCounts: {
      'TOYOTA|CAMRY|2019': 3, 'TOYOTA|RAV4|2019': 4, 'HONDA|CIVIC|2019': 3,
      'HONDA|ACCORD|2019': 4, 'HONDA|CR-V|2019': 5, 'FORD|F-150|2019': 8,
      'FORD|EXPLORER|2020': 9, 'CHEVROLET|EQUINOX|2018': 5, 'NISSAN|ROGUE|2018': 4,
      'JEEP|GRAND CHEROKEE|2019': 7, 'SUBARU|OUTBACK|2020': 3, 'TESLA|MODEL 3|2019': 6
    },

    /* Experian used-vehicle average APR by credit tier (%). */
    aprByTier: {
      superprime: 7.4, prime: 9.6, nearprime: 14.1, subprime: 18.9, deepsub: 21.6
    },

    /* EIA energy price fallbacks (live API supersedes when a key is configured). */
    energy: { gasUsdPerGal: 3.15, elecUsdPerKwh: 0.17 },

    constants: {
      stdMilesPerYear: 12000,   // valuation convention for "average" mileage
      regPerYear: 150,          // registration + inspection
      floorValue: 1500,         // running cars rarely trade below this
      cpmBenchmark: 0.45,       // cost-per-mile benchmark for scoring
      safetyCriticalComponents: [
        'AIR BAGS', 'SERVICE BRAKES', 'STEERING', 'FUEL SYSTEM',
        'SEAT BELTS', 'ELECTRICAL SYSTEM', 'POWER TRAIN', 'SUSPENSION', 'WHEELS'
      ]
    }
  };
}));
/* ==DATA-END== */
