/* Used Car Deal Analyzer — baked dataset (Appendix B schema).
 *
 * This block is REGENERATED by build_datasets.py. Values between the
 * DATA-START / DATA-END markers are machine-managed; edit the script, not this file.
 *
 * The `meta.sources` stamps say where each table came from and when. A table sourced
 * as "curated" is a hand-maintained transcription of published figures (cited in
 * README.md § Data sources) — it is the offline baseline. Running
 * `python3 build_datasets.py --refresh` on a machine with network access replaces
 * the fitted tables (vehicles, depCurves, mileSlopes, complaints, recallCounts)
 * with values derived from EPA / NHTSA / listing-corpus data.
 */
/* ==DATA-START== */
(function (root, factory) {
  var data = factory();
  if (typeof module === 'object' && module.exports) module.exports = data;
  else root.UCDA_DATA = data;
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  return {
    meta: {
      built: '2026-08-05',
      schema: 1,
      sources: {
        vehicles: 'curated (EPA fueleconomy.gov vehicles.csv subset, MY2010-2024)',
        brands: 'curated (RepairPal maintenance cost; Consumer Reports / JD Power reliability; iSeeCars longevity)',
        segments: 'curated (Bankrate/NerdWallet full-coverage premium averages; EPA class MPG)',
        depCurves: 'curated (iSeeCars 5-year depreciation by segment, back-solved to annual piecewise rates and pinned to that benchmark by test)',
        mileSlopes: 'curated (industry mileage-adjustment convention, banded by price)',
        complaints: 'curated (NHTSA ODI complaint volumes, representative model-years)',
        recallCounts: 'curated (NHTSA recall campaign counts, representative model-years)',
        aprByTier: 'curated (Experian State of the Automotive Finance Market, used-vehicle averages)',
        energy: 'curated (EIA weekly retail gasoline; EIA residential electricity average)'
      },
      // Tables older than this many months trigger a warning from `build_datasets.py --check`
      staleAfterMonths: 12
    },

    /* Brand-level maintenance cost, reliability baseline and expected service life.
     * maintPerYear: average annual maintenance + repair spend, USD
     * relBaseline:  composite reliability 0-100
     * lifeMiles:    typical useful life before major-repair economics dominate */
    brands: {
      'Toyota':        { maintPerYear: 441,  relBaseline: 90, lifeMiles: 250000 },
      'Lexus':         { maintPerYear: 551,  relBaseline: 92, lifeMiles: 250000 },
      'Honda':         { maintPerYear: 428,  relBaseline: 84, lifeMiles: 230000 },
      'Acura':         { maintPerYear: 501,  relBaseline: 80, lifeMiles: 220000 },
      'Mazda':         { maintPerYear: 462,  relBaseline: 86, lifeMiles: 220000 },
      'Subaru':        { maintPerYear: 617,  relBaseline: 79, lifeMiles: 220000 },
      'Hyundai':       { maintPerYear: 468,  relBaseline: 77, lifeMiles: 200000 },
      'Kia':           { maintPerYear: 474,  relBaseline: 78, lifeMiles: 200000 },
      'Nissan':        { maintPerYear: 500,  relBaseline: 70, lifeMiles: 200000 },
      'Infiniti':      { maintPerYear: 638,  relBaseline: 64, lifeMiles: 200000 },
      'Mitsubishi':    { maintPerYear: 535,  relBaseline: 68, lifeMiles: 190000 },
      'Ford':          { maintPerYear: 775,  relBaseline: 62, lifeMiles: 200000 },
      'Chevrolet':     { maintPerYear: 649,  relBaseline: 64, lifeMiles: 200000 },
      'GMC':           { maintPerYear: 744,  relBaseline: 62, lifeMiles: 200000 },
      'Buick':         { maintPerYear: 608,  relBaseline: 72, lifeMiles: 200000 },
      'Cadillac':      { maintPerYear: 783,  relBaseline: 54, lifeMiles: 190000 },
      'Ram':           { maintPerYear: 858,  relBaseline: 58, lifeMiles: 200000 },
      'Dodge':         { maintPerYear: 634,  relBaseline: 60, lifeMiles: 190000 },
      'Jeep':          { maintPerYear: 634,  relBaseline: 52, lifeMiles: 180000 },
      'Chrysler':      { maintPerYear: 608,  relBaseline: 56, lifeMiles: 180000 },
      'Volkswagen':    { maintPerYear: 676,  relBaseline: 60, lifeMiles: 180000 },
      'Audi':          { maintPerYear: 987,  relBaseline: 62, lifeMiles: 180000 },
      'BMW':           { maintPerYear: 968,  relBaseline: 66, lifeMiles: 180000 },
      'Mercedes-Benz': { maintPerYear: 908,  relBaseline: 58, lifeMiles: 190000 },
      'Volvo':         { maintPerYear: 769,  relBaseline: 56, lifeMiles: 200000 },
      'Mini':          { maintPerYear: 846,  relBaseline: 62, lifeMiles: 170000 },
      'Porsche':       { maintPerYear: 1192, relBaseline: 78, lifeMiles: 200000 },
      'Land Rover':    { maintPerYear: 1174, relBaseline: 40, lifeMiles: 150000 },
      'Lincoln':       { maintPerYear: 879,  relBaseline: 60, lifeMiles: 190000 },
      'Tesla':         { maintPerYear: 587,  relBaseline: 56, lifeMiles: 250000 },
      'Other':         { maintPerYear: 652,  relBaseline: 65, lifeMiles: 200000 }
    },

    /* Segment defaults. mpg/insPerYear are fallbacks when no per-model record exists.
     * evKwhPer100mi is set for electric segments (fuel math switches to electricity). */
    segments: {
      'Compact car':     { mpg: 32, insPerYear: 1700 },
      'Midsize car':     { mpg: 30, insPerYear: 1750 },
      'Compact SUV':     { mpg: 28, insPerYear: 1650 },
      'Midsize SUV':     { mpg: 22, insPerYear: 1800 },
      'Pickup truck':    { mpg: 20, insPerYear: 1850 },
      'Minivan':         { mpg: 24, insPerYear: 1700 },
      'Sports car':      { mpg: 24, insPerYear: 2300 },
      'Luxury':          { mpg: 24, insPerYear: 2200 },
      'Hybrid':          { mpg: 45, insPerYear: 1750 },
      'Electric':        { mpg: 0,  insPerYear: 1950, evKwhPer100mi: 33 }
    },

    /* Maintenance cost and service life vary enormously WITHIN a brand — a Camry and a
     * Tundra do not cost the same to keep. These scale the brand baseline by vehicle class.
     * tyres/brakes are the replacement cost for that class, used by the service schedule. */
    segmentFactors: {
      'Compact car':  { maint: 0.85, life: 1.00, tyres: 700,  brakes: 550,  belt: true },
      'Midsize car':  { maint: 0.95, life: 1.00, tyres: 850,  brakes: 620,  belt: true },
      'Compact SUV':  { maint: 1.00, life: 1.00, tyres: 900,  brakes: 650,  belt: true },
      'Midsize SUV':  { maint: 1.15, life: 0.95, tyres: 1150, brakes: 780,  belt: true },
      'Pickup truck': { maint: 1.20, life: 1.05, tyres: 1300, brakes: 850,  belt: true },
      'Minivan':      { maint: 1.05, life: 0.95, tyres: 950,  brakes: 700,  belt: true },
      'Sports car':   { maint: 1.35, life: 0.85, tyres: 1400, brakes: 1100, belt: true },
      'Luxury':       { maint: 1.30, life: 0.90, tyres: 1300, brakes: 950,  belt: true },
      'Hybrid':       { maint: 0.90, life: 1.05, tyres: 850,  brakes: 500,  belt: false },
      'Electric':     { maint: 0.65, life: 1.05, tyres: 1000, brakes: 450,  belt: false },
      'default':      { maint: 1.00, life: 1.00, tyres: 900,  brakes: 650,  belt: true }
    },

    /* Listing prices are ASKING prices. Cars transact below ask, so comps anchored to
     * listings bias fair value — and therefore the walk-away price — upward. This is the
     * haircut applied to comp-derived value, disclosed in the UI and adjustable there. */
    compBias: {
      askingToTransaction: 0.96,
      note: 'Listings are asking prices; used cars typically transact a few percent below ask.'
    },

    /* Wear items on a mileage clock. Costs are before the class multiplier below.
     * evSkip items do not exist on a battery-electric car. */
    serviceSchedule: [
      { name: 'Tyres (set of four)',        everyMiles: 45000,  costKey: 'tyres' },
      { name: 'Brake pads and rotors',      everyMiles: 50000,  costKey: 'brakes' },
      { name: 'Engine air and cabin filters', everyMiles: 30000, cost: 110 },
      { name: 'Brake fluid service',        everyMiles: 45000,  cost: 140 },
      { name: 'Starter battery',            everyMiles: 60000,  cost: 230 },
      { name: 'Transmission fluid service', everyMiles: 60000,  cost: 300, evSkip: true },
      { name: 'Spark plugs',                everyMiles: 100000, cost: 340, evSkip: true },
      { name: 'Coolant flush',              everyMiles: 100000, cost: 200 },
      { name: 'Shocks and struts',          everyMiles: 100000, cost: 950 },
      { name: 'Timing belt and water pump', everyMiles: 100000, cost: 950, evSkip: true,
        conditional: 'only if this engine uses a belt rather than a chain — ask before you buy' }
    ],

    /* State defaults. APPROXIMATE combined sales-tax averages and typical registration —
     * every one is editable in the UI and should be confirmed locally. tradeInCredit marks
     * states that tax only the price difference after a trade-in (the large majority).
     * propertyTaxRate is an annual tax on vehicle value where the state levies one. */
    states: {
      verifyNote: 'Approximate defaults — confirm your local figures; every field stays editable.',
      // ins      insurance cost index, 1.00 = national average
      // gas/elec typical retail fuel price and residential electricity rate
      // evFee    annual registration surcharge on electric vehicles
      // inspect  state safety/emissions inspection cadence and typical cost
      // titleFee one-time title and plate transfer charge at purchase
      rates: {
        AL: { tax: 0.052, tradeInCredit: true,  reg: 100, propertyTaxRate: 0, ins: 0.95, gas: 2.75, elec: 0.15, evFee: 200, inspect: { cadence: 'none', cost: 0 }, titleFee: 18 },
        AK: { tax: 0.018, tradeInCredit: true,  reg: 120, propertyTaxRate: 0, ins: 0.85, gas: 3.70, elec: 0.24, evFee: 0, inspect: { cadence: 'none', cost: 0 }, titleFee: 15 },
        AZ: { tax: 0.084, tradeInCredit: true,  reg: 150, propertyTaxRate: 0, ins: 1.05, gas: 3.45, elec: 0.15, evFee: 0, inspect: { cadence: 'biennial', cost: 27 }, titleFee: 4 },
        AR: { tax: 0.095, tradeInCredit: true,  reg: 110, propertyTaxRate: 0, ins: 1.00, gas: 2.80, elec: 0.12, evFee: 200, inspect: { cadence: 'none', cost: 0 }, titleFee: 10 },
        CA: { tax: 0.088, tradeInCredit: false, reg: 350, propertyTaxRate: 0, ins: 1.20, gas: 4.60, elec: 0.30, evFee: 118, inspect: { cadence: 'biennial', cost: 55 }, titleFee: 23 },
        CO: { tax: 0.078, tradeInCredit: true,  reg: 400, propertyTaxRate: 0, ins: 1.25, gas: 3.15, elec: 0.15, evFee: 54, inspect: { cadence: 'biennial', cost: 25 }, titleFee: 8 },
        CT: { tax: 0.064, tradeInCredit: true,  reg: 120, propertyTaxRate: 0.020, ins: 1.20, gas: 3.30, elec: 0.30, evFee: 0, inspect: { cadence: 'biennial', cost: 20 }, titleFee: 25 },
        DE: { tax: 0.043, tradeInCredit: true,  reg: 100, propertyTaxRate: 0, ins: 1.30, gas: 3.05, elec: 0.16, evFee: 0, inspect: { cadence: 'biennial', cost: 0 }, titleFee: 35 },
        FL: { tax: 0.070, tradeInCredit: true,  reg: 225, propertyTaxRate: 0, ins: 1.65, gas: 3.10, elec: 0.15, evFee: 0, inspect: { cadence: 'none', cost: 0 }, titleFee: 78 },
        GA: { tax: 0.070, tradeInCredit: true,  reg: 100, propertyTaxRate: 0, ins: 1.15, gas: 2.95, elec: 0.14, evFee: 215, inspect: { cadence: 'annual', cost: 25 }, titleFee: 18 },
        HI: { tax: 0.045, tradeInCredit: false, reg: 250, propertyTaxRate: 0, ins: 0.75, gas: 4.60, elec: 0.42, evFee: 50, inspect: { cadence: 'annual', cost: 25 }, titleFee: 10 },
        ID: { tax: 0.060, tradeInCredit: true,  reg: 120, propertyTaxRate: 0, ins: 0.60, gas: 3.55, elec: 0.11, evFee: 140, inspect: { cadence: 'none', cost: 0 }, titleFee: 14 },
        IL: { tax: 0.089, tradeInCredit: true,  reg: 210, propertyTaxRate: 0, ins: 0.95, gas: 3.45, elec: 0.16, evFee: 251, inspect: { cadence: 'biennial', cost: 0 }, titleFee: 165 },
        IN: { tax: 0.070, tradeInCredit: true,  reg: 130, propertyTaxRate: 0, ins: 0.75, gas: 3.05, elec: 0.15, evFee: 221, inspect: { cadence: 'none', cost: 0 }, titleFee: 15 },
        IA: { tax: 0.069, tradeInCredit: true,  reg: 150, propertyTaxRate: 0, ins: 0.65, gas: 2.95, elec: 0.13, evFee: 130, inspect: { cadence: 'none', cost: 0 }, titleFee: 25 },
        KS: { tax: 0.087, tradeInCredit: true,  reg: 130, propertyTaxRate: 0.015, ins: 0.90, gas: 2.85, elec: 0.14, evFee: 100, inspect: { cadence: 'none', cost: 0 }, titleFee: 10 },
        KY: { tax: 0.060, tradeInCredit: false, reg: 120, propertyTaxRate: 0.012, ins: 1.20, gas: 2.90, elec: 0.13, evFee: 120, inspect: { cadence: 'none', cost: 0 }, titleFee: 9 },
        LA: { tax: 0.095, tradeInCredit: true,  reg: 100, propertyTaxRate: 0, ins: 1.75, gas: 2.80, elec: 0.12, evFee: 110, inspect: { cadence: 'annual', cost: 20 }, titleFee: 69 },
        ME: { tax: 0.055, tradeInCredit: true,  reg: 120, propertyTaxRate: 0.018, ins: 0.55, gas: 3.20, elec: 0.25, evFee: 0, inspect: { cadence: 'annual', cost: 18 }, titleFee: 33 },
        MD: { tax: 0.060, tradeInCredit: false, reg: 190, propertyTaxRate: 0, ins: 1.25, gas: 3.15, elec: 0.18, evFee: 0, inspect: { cadence: 'biennial', cost: 14 }, titleFee: 100 },
        MA: { tax: 0.063, tradeInCredit: true,  reg: 120, propertyTaxRate: 0.015, ins: 0.95, gas: 3.25, elec: 0.30, evFee: 0, inspect: { cadence: 'annual', cost: 35 }, titleFee: 75 },
        MI: { tax: 0.060, tradeInCredit: false, reg: 200, propertyTaxRate: 0, ins: 1.90, gas: 3.15, elec: 0.19, evFee: 140, inspect: { cadence: 'none', cost: 0 }, titleFee: 15 },
        MN: { tax: 0.075, tradeInCredit: true,  reg: 200, propertyTaxRate: 0, ins: 0.85, gas: 3.05, elec: 0.15, evFee: 75, inspect: { cadence: 'none', cost: 0 }, titleFee: 9 },
        MS: { tax: 0.072, tradeInCredit: true,  reg: 110, propertyTaxRate: 0.015, ins: 1.05, gas: 2.70, elec: 0.13, evFee: 150, inspect: { cadence: 'none', cost: 0 }, titleFee: 9 },
        MO: { tax: 0.082, tradeInCredit: true,  reg: 110, propertyTaxRate: 0.020, ins: 1.00, gas: 2.80, elec: 0.12, evFee: 90, inspect: { cadence: 'biennial', cost: 24 }, titleFee: 11 },
        MT: { tax: 0.000, tradeInCredit: true,  reg: 220, propertyTaxRate: 0, ins: 0.80, gas: 3.25, elec: 0.12, evFee: 0, inspect: { cadence: 'none', cost: 0 }, titleFee: 12 },
        NE: { tax: 0.069, tradeInCredit: true,  reg: 150, propertyTaxRate: 0.015, ins: 0.85, gas: 2.95, elec: 0.11, evFee: 75, inspect: { cadence: 'none', cost: 0 }, titleFee: 10 },
        NV: { tax: 0.083, tradeInCredit: true,  reg: 300, propertyTaxRate: 0, ins: 1.35, gas: 3.90, elec: 0.16, evFee: 0, inspect: { cadence: 'annual', cost: 30 }, titleFee: 29 },
        NH: { tax: 0.000, tradeInCredit: true,  reg: 220, propertyTaxRate: 0, ins: 0.65, gas: 3.10, elec: 0.25, evFee: 0, inspect: { cadence: 'annual', cost: 50 }, titleFee: 25 },
        NJ: { tax: 0.066, tradeInCredit: true,  reg: 120, propertyTaxRate: 0, ins: 1.25, gas: 3.20, elec: 0.19, evFee: 0, inspect: { cadence: 'biennial', cost: 0 }, titleFee: 60 },
        NM: { tax: 0.078, tradeInCredit: true,  reg: 100, propertyTaxRate: 0, ins: 0.95, gas: 2.95, elec: 0.15, evFee: 0, inspect: { cadence: 'none', cost: 0 }, titleFee: 17 },
        NY: { tax: 0.085, tradeInCredit: true,  reg: 130, propertyTaxRate: 0, ins: 1.35, gas: 3.35, elec: 0.24, evFee: 0, inspect: { cadence: 'annual', cost: 37 }, titleFee: 50 },
        NC: { tax: 0.030, tradeInCredit: true,  reg: 140, propertyTaxRate: 0.012, ins: 0.80, gas: 2.95, elec: 0.13, evFee: 180, inspect: { cadence: 'annual', cost: 30 }, titleFee: 56 },
        ND: { tax: 0.070, tradeInCredit: true,  reg: 110, propertyTaxRate: 0, ins: 0.70, gas: 3.05, elec: 0.11, evFee: 120, inspect: { cadence: 'none', cost: 0 }, titleFee: 5 },
        OH: { tax: 0.073, tradeInCredit: true,  reg: 110, propertyTaxRate: 0, ins: 0.65, gas: 3.05, elec: 0.16, evFee: 200, inspect: { cadence: 'biennial', cost: 0 }, titleFee: 15 },
        OK: { tax: 0.090, tradeInCredit: true,  reg: 150, propertyTaxRate: 0, ins: 1.05, gas: 2.75, elec: 0.12, evFee: 110, inspect: { cadence: 'none', cost: 0 }, titleFee: 11 },
        OR: { tax: 0.000, tradeInCredit: true,  reg: 250, propertyTaxRate: 0, ins: 0.85, gas: 3.90, elec: 0.13, evFee: 115, inspect: { cadence: 'none', cost: 0 }, titleFee: 101 },
        PA: { tax: 0.063, tradeInCredit: true,  reg: 110, propertyTaxRate: 0, ins: 0.95, gas: 3.50, elec: 0.18, evFee: 0, inspect: { cadence: 'annual', cost: 40 }, titleFee: 58 },
        RI: { tax: 0.070, tradeInCredit: true,  reg: 120, propertyTaxRate: 0.020, ins: 1.30, gas: 3.20, elec: 0.29, evFee: 0, inspect: { cadence: 'biennial', cost: 55 }, titleFee: 53 },
        SC: { tax: 0.075, tradeInCredit: true,  reg: 100, propertyTaxRate: 0.017, ins: 1.15, gas: 2.85, elec: 0.14, evFee: 120, inspect: { cadence: 'none', cost: 0 }, titleFee: 15 },
        SD: { tax: 0.064, tradeInCredit: true,  reg: 110, propertyTaxRate: 0, ins: 0.75, gas: 3.00, elec: 0.13, evFee: 50, inspect: { cadence: 'none', cost: 0 }, titleFee: 10 },
        TN: { tax: 0.095, tradeInCredit: true,  reg: 110, propertyTaxRate: 0, ins: 0.85, gas: 2.80, elec: 0.12, evFee: 100, inspect: { cadence: 'none', cost: 0 }, titleFee: 11 },
        TX: { tax: 0.082, tradeInCredit: true,  reg: 150, propertyTaxRate: 0, ins: 1.15, gas: 2.75, elec: 0.15, evFee: 200, inspect: { cadence: 'annual', cost: 25 }, titleFee: 33 },
        UT: { tax: 0.072, tradeInCredit: true,  reg: 150, propertyTaxRate: 0, ins: 0.90, gas: 3.45, elec: 0.11, evFee: 120, inspect: { cadence: 'biennial', cost: 25 }, titleFee: 6 },
        VT: { tax: 0.062, tradeInCredit: true,  reg: 140, propertyTaxRate: 0, ins: 0.60, gas: 3.30, elec: 0.21, evFee: 89, inspect: { cadence: 'annual', cost: 45 }, titleFee: 35 },
        VA: { tax: 0.043, tradeInCredit: false, reg: 110, propertyTaxRate: 0.035, ins: 0.80, gas: 2.95, elec: 0.14, evFee: 109, inspect: { cadence: 'annual', cost: 20 }, titleFee: 15 },
        WA: { tax: 0.092, tradeInCredit: true,  reg: 250, propertyTaxRate: 0, ins: 0.90, gas: 4.20, elec: 0.11, evFee: 225, inspect: { cadence: 'none', cost: 0 }, titleFee: 15 },
        WV: { tax: 0.065, tradeInCredit: true,  reg: 110, propertyTaxRate: 0, ins: 0.95, gas: 3.05, elec: 0.15, evFee: 200, inspect: { cadence: 'annual', cost: 15 }, titleFee: 15 },
        WI: { tax: 0.055, tradeInCredit: true,  reg: 150, propertyTaxRate: 0, ins: 0.70, gas: 3.05, elec: 0.17, evFee: 175, inspect: { cadence: 'biennial', cost: 0 }, titleFee: 165 },
        WY: { tax: 0.054, tradeInCredit: true,  reg: 150, propertyTaxRate: 0.015, ins: 0.70, gas: 3.20, elec: 0.11, evFee: 200, inspect: { cadence: 'none', cost: 0 }, titleFee: 15 }
      }
    },

    /* Piecewise annual depreciation rates by segment (fraction of current value per year),
     * with knots at ages 5, 8 and 12 — the observed old-car slowdown.
     * brandAdj shifts the rate additively (clamped +/-0.03 by the engine). */
    depCurves: {
      'Compact car':   { r1_5: 0.113, r6_8: 0.091, r9_12: 0.069, r13p: 0.051 },
      'Midsize car':   { r1_5: 0.123, r6_8: 0.099, r9_12: 0.075, r13p: 0.055 },
      'Compact SUV':   { r1_5: 0.113, r6_8: 0.091, r9_12: 0.069, r13p: 0.051 },
      'Midsize SUV':   { r1_5: 0.129, r6_8: 0.105, r9_12: 0.079, r13p: 0.058 },
      'Pickup truck':  { r1_5: 0.097, r6_8: 0.079, r9_12: 0.059, r13p: 0.044 },
      'Minivan':       { r1_5: 0.137, r6_8: 0.111, r9_12: 0.083, r13p: 0.061 },
      'Sports car':    { r1_5: 0.129, r6_8: 0.105, r9_12: 0.079, r13p: 0.058 },
      'Luxury':        { r1_5: 0.148, r6_8: 0.120, r9_12: 0.090, r13p: 0.066 },
      'Hybrid':        { r1_5: 0.113, r6_8: 0.091, r9_12: 0.069, r13p: 0.051 },
      'Electric':      { r1_5: 0.140, r6_8: 0.114, r9_12: 0.085, r13p: 0.063 },
      brandAdj: {
        'Toyota': -0.013, 'Lexus': -0.010, 'Honda': -0.011, 'Subaru': -0.009,
        'Mazda': -0.006, 'Porsche': -0.012, 'Tesla': 0.010, 'Jeep': 0.006,
        'Nissan': 0.008, 'Chrysler': 0.012, 'Cadillac': 0.014, 'Lincoln': 0.014,
        'Infiniti': 0.013, 'Land Rover': 0.024, 'BMW': 0.018, 'Mercedes-Benz': 0.018,
        'Audi': 0.016, 'Volvo': 0.013, 'Mini': 0.011
      }
    },

    /* Dollar-per-mile adjustment when odometer deviates from the age-expected mileage,
     * banded by vehicle price. Engine clamps to [0.02, 0.25]. */
    mileSlopes: {
      'default': [
        { maxPrice: 8000,   usdPerMile: 0.035 },
        { maxPrice: 15000,  usdPerMile: 0.060 },
        { maxPrice: 25000,  usdPerMile: 0.090 },
        { maxPrice: 40000,  usdPerMile: 0.130 },
        { maxPrice: 999999, usdPerMile: 0.180 }
      ],
      'Pickup truck': [
        { maxPrice: 15000,  usdPerMile: 0.050 },
        { maxPrice: 30000,  usdPerMile: 0.080 },
        { maxPrice: 999999, usdPerMile: 0.120 }
      ],
      'Luxury': [
        { maxPrice: 15000,  usdPerMile: 0.080 },
        { maxPrice: 30000,  usdPerMile: 0.140 },
        { maxPrice: 999999, usdPerMile: 0.200 }
      ]
    },

    /* Per-model EPA figures + segment mapping. Keyed make -> model -> year.
     * `build_datasets.py --refresh` expands this from the full EPA vehicles.csv. */
    vehicles: {
      'Toyota': {
        'Camry':     { seg: 'Midsize car', years: { 2015: 28, 2017: 29, 2019: 32, 2021: 32, 2023: 32 } },
        'Corolla':   { seg: 'Compact car', years: { 2015: 31, 2017: 32, 2019: 34, 2021: 35, 2023: 35 } },
        'RAV4':      { seg: 'Compact SUV', years: { 2015: 26, 2017: 26, 2019: 30, 2021: 30, 2023: 30 } },
        'Highlander':{ seg: 'Midsize SUV', years: { 2015: 21, 2017: 22, 2019: 23, 2021: 24, 2023: 24 } },
        'Tacoma':    { seg: 'Pickup truck', years: { 2015: 21, 2017: 21, 2019: 21, 2021: 21, 2023: 21 } },
        'Tundra':    { seg: 'Pickup truck', years: { 2015: 15, 2017: 15, 2019: 15, 2021: 15, 2023: 20 } },
        'Sienna':    { seg: 'Minivan', years: { 2015: 21, 2017: 21, 2019: 22, 2021: 36, 2023: 36 } },
        'Prius':     { seg: 'Hybrid', years: { 2015: 50, 2017: 52, 2019: 52, 2021: 52, 2023: 57 } }
      },
      'Honda': {
        'Civic':     { seg: 'Compact car', years: { 2015: 33, 2017: 35, 2019: 36, 2021: 36, 2023: 35 } },
        'Accord':    { seg: 'Midsize car', years: { 2015: 31, 2017: 31, 2019: 33, 2021: 33, 2023: 32 } },
        'CR-V':      { seg: 'Compact SUV', years: { 2015: 29, 2017: 30, 2019: 30, 2021: 30, 2023: 30 } },
        'Pilot':     { seg: 'Midsize SUV', years: { 2015: 21, 2017: 22, 2019: 22, 2021: 22, 2023: 22 } },
        'Odyssey':   { seg: 'Minivan', years: { 2015: 22, 2017: 22, 2019: 22, 2021: 22, 2023: 22 } }
      },
      'Ford': {
        'F-150':     { seg: 'Pickup truck', years: { 2015: 19, 2017: 20, 2019: 21, 2021: 22, 2023: 22 } },
        'Escape':    { seg: 'Compact SUV', years: { 2015: 25, 2017: 26, 2019: 26, 2021: 30, 2023: 30 } },
        'Explorer':  { seg: 'Midsize SUV', years: { 2015: 20, 2017: 20, 2019: 21, 2021: 24, 2023: 24 } },
        'Fusion':    { seg: 'Midsize car', years: { 2015: 26, 2017: 26, 2019: 27, 2021: 27 } },
        'Mustang':   { seg: 'Sports car', years: { 2015: 20, 2017: 21, 2019: 21, 2021: 22, 2023: 22 } }
      },
      'Chevrolet': {
        'Silverado 1500': { seg: 'Pickup truck', years: { 2015: 18, 2017: 19, 2019: 19, 2021: 20, 2023: 20 } },
        'Equinox':   { seg: 'Compact SUV', years: { 2015: 24, 2017: 26, 2019: 28, 2021: 28, 2023: 28 } },
        'Malibu':    { seg: 'Midsize car', years: { 2015: 29, 2017: 32, 2019: 32, 2021: 32, 2023: 32 } },
        'Tahoe':     { seg: 'Midsize SUV', years: { 2015: 18, 2017: 18, 2019: 18, 2021: 18, 2023: 18 } },
        'Bolt EV':   { seg: 'Electric', years: { 2017: 0, 2019: 0, 2021: 0, 2023: 0 }, kwhPer100mi: 28 }
      },
      'Nissan': {
        'Altima':    { seg: 'Midsize car', years: { 2015: 31, 2017: 31, 2019: 32, 2021: 32, 2023: 32 } },
        'Rogue':     { seg: 'Compact SUV', years: { 2015: 28, 2017: 29, 2019: 29, 2021: 30, 2023: 33 } },
        'Sentra':    { seg: 'Compact car', years: { 2015: 33, 2017: 32, 2019: 32, 2021: 33, 2023: 33 } },
        'Leaf':      { seg: 'Electric', years: { 2015: 0, 2017: 0, 2019: 0, 2021: 0, 2023: 0 }, kwhPer100mi: 30 }
      },
      'Subaru': {
        'Outback':   { seg: 'Compact SUV', years: { 2015: 28, 2017: 28, 2019: 29, 2021: 29, 2023: 29 } },
        'Forester':  { seg: 'Compact SUV', years: { 2015: 28, 2017: 28, 2019: 29, 2021: 29, 2023: 29 } },
        'Impreza':   { seg: 'Compact car', years: { 2015: 31, 2017: 31, 2019: 31, 2021: 31, 2023: 31 } },
        'Crosstrek': { seg: 'Compact SUV', years: { 2017: 29, 2019: 30, 2021: 30, 2023: 29 } }
      },
      'Tesla': {
        'Model 3':   { seg: 'Electric', years: { 2019: 0, 2021: 0, 2023: 0 }, kwhPer100mi: 25 },
        'Model Y':   { seg: 'Electric', years: { 2021: 0, 2023: 0 }, kwhPer100mi: 28 },
        'Model S':   { seg: 'Electric', years: { 2015: 0, 2017: 0, 2019: 0, 2021: 0 }, kwhPer100mi: 33 }
      },
      'Jeep': {
        'Grand Cherokee': { seg: 'Midsize SUV', years: { 2015: 21, 2017: 21, 2019: 21, 2021: 22, 2023: 22 } },
        'Wrangler':  { seg: 'Midsize SUV', years: { 2015: 19, 2017: 19, 2019: 21, 2021: 22, 2023: 22 } },
        'Cherokee':  { seg: 'Compact SUV', years: { 2015: 24, 2017: 24, 2019: 25, 2021: 25, 2023: 25 } }
      },
      'BMW': {
        '3 Series':  { seg: 'Luxury', years: { 2015: 27, 2017: 28, 2019: 30, 2021: 30, 2023: 30 } },
        '5 Series':  { seg: 'Luxury', years: { 2015: 26, 2017: 27, 2019: 28, 2021: 28, 2023: 28 } },
        'X3':        { seg: 'Luxury', years: { 2015: 24, 2017: 25, 2019: 26, 2021: 26, 2023: 26 } },
        'X5':        { seg: 'Luxury', years: { 2015: 21, 2017: 22, 2019: 23, 2021: 24, 2023: 24 } }
      },
      'Hyundai': {
        'Elantra':   { seg: 'Compact car', years: { 2015: 32, 2017: 32, 2019: 35, 2021: 37, 2023: 37 } },
        'Sonata':    { seg: 'Midsize car', years: { 2015: 29, 2017: 30, 2019: 31, 2021: 32, 2023: 32 } },
        'Tucson':    { seg: 'Compact SUV', years: { 2015: 25, 2017: 26, 2019: 26, 2021: 26, 2023: 28 } },
        'Santa Fe':  { seg: 'Midsize SUV', years: { 2015: 21, 2017: 22, 2019: 25, 2021: 25, 2023: 25 } }
      },
      'Kia': {
        'Optima':    { seg: 'Midsize car', years: { 2015: 27, 2017: 29, 2019: 31, 2021: 31 } },
        'Soul':      { seg: 'Compact car', years: { 2015: 27, 2017: 28, 2019: 29, 2021: 30, 2023: 30 } },
        'Sorento':   { seg: 'Midsize SUV', years: { 2015: 21, 2017: 22, 2019: 22, 2021: 24, 2023: 24 } },
        'Telluride': { seg: 'Midsize SUV', years: { 2020: 23, 2021: 23, 2023: 23 } }
      },
      'Mazda': {
        'Mazda3':    { seg: 'Compact car', years: { 2015: 33, 2017: 32, 2019: 30, 2021: 30, 2023: 30 } },
        'CX-5':      { seg: 'Compact SUV', years: { 2015: 28, 2017: 27, 2019: 28, 2021: 28, 2023: 28 } },
        'Mazda6':    { seg: 'Midsize car', years: { 2015: 30, 2017: 30, 2019: 29, 2021: 29 } }
      }
    },

    /* NHTSA ODI complaint volumes for representative model-years.
     * Key: "MAKE|MODEL|YEAR". `per100k` is the normalized rate used by the score;
     * `segP90` is the 90th-percentile rate within the segment (the score's scale anchor). */
    complaints: {
      'TOYOTA|CAMRY|2019':      { count: 61,  per100k: 14.2, top: ['ELECTRICAL SYSTEM', 'POWERTRAIN'] },
      'TOYOTA|COROLLA|2019':    { count: 44,  per100k: 11.8, top: ['ELECTRICAL SYSTEM'] },
      'TOYOTA|RAV4|2019':       { count: 214, per100k: 38.4, top: ['POWERTRAIN', 'FUEL SYSTEM'] },
      'HONDA|CIVIC|2019':       { count: 132, per100k: 27.1, top: ['ELECTRICAL SYSTEM', 'STRUCTURE'] },
      'HONDA|ACCORD|2019':      { count: 178, per100k: 41.3, top: ['ELECTRICAL SYSTEM', 'ENGINE'] },
      'HONDA|CR-V|2019':        { count: 246, per100k: 46.9, top: ['ENGINE', 'FUEL SYSTEM'] },
      'FORD|F-150|2019':        { count: 389, per100k: 52.7, top: ['POWERTRAIN', 'ELECTRICAL SYSTEM'] },
      'FORD|EXPLORER|2020':     { count: 612, per100k: 98.4, top: ['POWERTRAIN', 'STRUCTURE', 'ELECTRICAL SYSTEM'] },
      'CHEVROLET|EQUINOX|2018': { count: 421, per100k: 76.2, top: ['ENGINE', 'POWERTRAIN'] },
      'NISSAN|ROGUE|2018':      { count: 358, per100k: 64.5, top: ['POWERTRAIN', 'FORWARD COLLISION AVOIDANCE'] },
      'NISSAN|ALTIMA|2019':     { count: 197, per100k: 48.2, top: ['POWERTRAIN'] },
      'JEEP|GRAND CHEROKEE|2019': { count: 288, per100k: 71.3, top: ['ELECTRICAL SYSTEM', 'POWERTRAIN'] },
      'SUBARU|OUTBACK|2020':    { count: 341, per100k: 69.8, top: ['ELECTRICAL SYSTEM', 'VISIBILITY'] },
      'TESLA|MODEL 3|2019':     { count: 156, per100k: 33.6, top: ['STRUCTURE', 'ELECTRICAL SYSTEM'] }
    },

    /* Segment 90th-percentile complaint rates — the denominator for the reliability blend. */
    complaintSegP90: {
      'Compact car': 60, 'Midsize car': 70, 'Compact SUV': 75, 'Midsize SUV': 95,
      'Pickup truck': 85, 'Minivan': 80, 'Sports car': 55, 'Luxury': 65,
      'Hybrid': 55, 'Electric': 60, 'default': 70
    },

    /* Offline fallback for open-recall counts (live NHTSA API supersedes when reachable). */
    recallCounts: {
      'TOYOTA|CAMRY|2019': 3, 'TOYOTA|RAV4|2019': 4, 'HONDA|CIVIC|2019': 3,
      'HONDA|ACCORD|2019': 4, 'HONDA|CR-V|2019': 5, 'FORD|F-150|2019': 8,
      'FORD|EXPLORER|2020': 9, 'CHEVROLET|EQUINOX|2018': 5, 'NISSAN|ROGUE|2018': 4,
      'JEEP|GRAND CHEROKEE|2019': 7, 'SUBARU|OUTBACK|2020': 3, 'TESLA|MODEL 3|2019': 6
    },

    /* Experian used-vehicle average APR by credit tier (%). */
    aprByTier: {
      superprime: 7.4, prime: 9.6, nearprime: 14.1, subprime: 18.9, deepsub: 21.6
    },

    /* EIA energy price fallbacks (live API supersedes when a key is configured). */
    energy: { gasUsdPerGal: 3.15, elecUsdPerKwh: 0.17 },

    constants: {
      stdMilesPerYear: 12000,   // valuation convention for "average" mileage
      regPerYear: 150,          // registration + inspection
      floorValue: 1500,         // running cars rarely trade below this
      cpmBenchmark: 0.45,       // cost-per-mile benchmark for scoring
      safetyCriticalComponents: [
        'AIR BAGS', 'SERVICE BRAKES', 'STEERING', 'FUEL SYSTEM',
        'SEAT BELTS', 'ELECTRICAL SYSTEM', 'POWER TRAIN', 'SUSPENSION', 'WHEELS'
      ]
    }
  };
}));
/* ==DATA-END== */
