#!/usr/bin/env python3
"""Build the Used Car Deal Analyzer's listing database.

The analyzer scores one car at a time. Feed it a few hundred listings and it can rank a
whole market and derive real comparables from the cohort instead of asking you to type
them in. This script is how listings get in.

Three ways to supply them
-------------------------
1. **An assistant browses for you.** Claude searches the web, reads listing pages and
   emits JSON in the schema below (see AGENTS.md for the exact contract), then::

       python3 scrape_listings.py --from-json found.json --merge

2. **Fetch pages directly.** Extracts schema.org ``Vehicle``/``Car`` JSON-LD, which
   listing sites publish specifically so machines can read it::

       python3 scrape_listings.py --fetch https://example.com/listing/123 ...

3. **A spreadsheet export.** ``--from-csv export.csv`` with columns matching the schema.

Output is ``listings.js`` (loadable from ``file://`` by the browser tool) and
``listings.json`` (for anything else).

Politeness and terms of use
---------------------------
``--fetch`` honours ``robots.txt``, rate-limits itself, identifies itself honestly in the
User-Agent, and refuses paths it is disallowed from. It is built for reading a handful of
pages you are already shopping, at human speed. Many listing sites restrict automated
collection in their terms; complying with those terms is the operator's responsibility.
Where a site offers an API (Marketcheck, Auto.dev), prefer it.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import urllib.robotparser
from datetime import date, datetime
from typing import Any, Dict, Iterable, List, Optional, Sequence

logger = logging.getLogger(__name__)

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_JS = os.path.join(HERE, "listings.js")
DEFAULT_JSON = os.path.join(HERE, "listings.json")

SCHEMA_VERSION = 1
USER_AGENT = ("UsedCarDealAnalyzer/1.0 (personal car shopping; "
              "https://github.com/brennansk1/Car-Calculator---Utah-County)")
REQUEST_DELAY_SECONDS = 2.0

#: Fields the browser tool understands. Anything else is carried through in `notes`.
FIELDS = [
    "id", "vin", "year", "make", "model", "trim", "miles", "price", "title", "accidents",
    "owners", "condition", "seller", "dealer", "city", "state", "zip", "distance",
    "daysOnMarket", "priceDrop", "url", "source", "seenAt", "mpg", "segment", "notes",
]

JS_HEADER = """/* Used Car Deal Analyzer — scraped listing database.
 *
 * GENERATED by scrape_listings.py. Do not hand-edit; re-run the script instead.
 * Loaded by index.html as a plain script so it works from file:// with no server.
 *
 * Every listing is an asking price observed at a point in time, not a sale price.
 * The analyzer discounts them accordingly.
 */
"""


class FetchError(Exception):
    """A page could not be retrieved or was disallowed."""


# --------------------------------------------------------------------- parsing


def _num(value: Any) -> Optional[float]:
    """Pull a number out of '$18,500', '52,341 mi', 18500 or None."""
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value) if value == value else None  # NaN check
    cleaned = re.sub(r"[^0-9.\-]", "", str(value))
    if cleaned in ("", "-", ".", "-."):
        return None
    try:
        return float(cleaned)
    except ValueError:
        return None


def _text(value: Any) -> str:
    return "" if value is None else str(value).strip()


#: Field names an assistant might reasonably use, mapped onto ours.
ALIASES: Dict[str, Sequence[str]] = {
    "year": ("year", "modelYear", "model_year", "yr"),
    "make": ("make", "brand", "manufacturer"),
    "model": ("model", "modelName", "model_name"),
    "trim": ("trim", "trimLevel", "trim_level", "version"),
    "miles": ("miles", "mileage", "odometer", "odometerReading", "miles_driven"),
    "price": ("price", "askingPrice", "asking_price", "listPrice", "list_price", "cost"),
    "vin": ("vin", "VIN", "vehicleIdentificationNumber"),
    "url": ("url", "link", "href", "listingUrl", "listing_url", "webpage", "website", "page"),
    "source": ("source", "site", "siteName", "domain", "marketplace"),
    "dealer": ("dealer", "dealerName", "dealer_name", "sellerName", "seller_name", "store"),
    "city": ("city", "town", "locality"),
    "state": ("state", "region", "province"),
    "zip": ("zip", "zipcode", "zip_code", "postalCode", "postal_code"),
    "distance": ("distance", "distanceMiles", "miles_away", "milesAway"),
    "title": ("title", "titleStatus", "title_status", "titleType"),
    "accidents": ("accidents", "accidentHistory", "accident_history", "accident", "damage"),
    "owners": ("owners", "numOwners", "num_owners", "previousOwners", "ownerCount"),
    "condition": ("condition", "vehicleCondition"),
    "seller": ("seller", "sellerType", "seller_type", "listedBy"),
    "daysOnMarket": ("daysOnMarket", "days_on_market", "daysListed", "dom"),
    "priceDrop": ("priceDrop", "price_drop", "priceReduction"),
    "mpg": ("mpg", "combinedMpg", "combined_mpg", "fuelEconomy"),
    "segment": ("segment", "bodyStyle", "body_style", "bodyType", "category"),
    "notes": ("notes", "description", "summary", "comments", "headline"),
    "id": ("id", "listingId", "listing_id", "stockNumber", "stock"),
}

FENCE_RE = re.compile(r"```(?:[a-zA-Z]+)?\s*(.*?)```", re.DOTALL)


def parse_text(raw: str) -> List[Dict[str, Any]]:
    """Read listings out of whatever an assistant produced.

    Accepts a JSON array or envelope, JSON wrapped in a markdown fence, JSON surrounded by
    prose, one JSON object per line, or a delimited table with a header row. Rejecting all
    but one shape would just push the cleanup onto the operator.
    """
    text = (raw or "").strip()
    if not text:
        return []

    fenced = FENCE_RE.search(text)
    if fenced:
        text = fenced.group(1).strip()

    def unwrap(payload: Any) -> List[Dict[str, Any]]:
        if isinstance(payload, list):
            return [r for r in payload if isinstance(r, dict)]
        if isinstance(payload, dict):
            return [r for r in payload.get("listings", []) if isinstance(r, dict)]
        return []

    try:
        return unwrap(json.loads(text))
    except json.JSONDecodeError:
        pass

    # JSON embedded in prose: take the outermost bracketed span.
    starts = [i for i in (text.find("{"), text.find("[")) if i != -1]
    if starts:
        start = min(starts)
        closer = "]" if text[start] == "[" else "}"
        end = text.rfind(closer)
        if end > start:
            try:
                return unwrap(json.loads(text[start:end + 1]))
            except json.JSONDecodeError:
                pass

    lines = [line.strip() for line in text.splitlines() if line.strip()]

    # One JSON object per line.
    ndjson: List[Dict[str, Any]] = []
    for line in lines:
        try:
            obj = json.loads(line.rstrip(","))
        except json.JSONDecodeError:
            ndjson = []
            break
        if not isinstance(obj, dict):
            ndjson = []
            break
        ndjson.append(obj)
    if ndjson:
        return ndjson

    # A delimited table.
    if len(lines) > 1:
        delimiter = "\t" if "\t" in lines[0] else ("," if "," in lines[0] else None)
        if delimiter:
            reader = csv.DictReader(lines, delimiter=delimiter)
            rows = [dict(r) for r in reader]
            if rows:
                return rows
    return []


def _pick(record: Dict[str, Any], field: str) -> Any:
    """First non-empty value among a field's accepted names, case-insensitively."""
    for name in ALIASES.get(field, (field,)):
        value = record.get(name)
        if value not in (None, ""):
            return value
    folded = {re.sub(r"[^a-z]", "", k.lower()): v for k, v in record.items()}
    for name in ALIASES.get(field, (field,)):
        value = folded.get(re.sub(r"[^a-z]", "", name.lower()))
        if value not in (None, ""):
            return value
    return None


def normalise_url(value: Any) -> Optional[str]:
    """Keep real http(s) links; give a bare domain a scheme so it stays clickable."""
    text = _text(value)
    if not text:
        return None
    if re.match(r"^https?://", text, re.I):
        return text
    if re.match(r"^[\w.-]+\.[a-z]{2,}(/|$)", text, re.I):
        return "https://" + text
    return None


def host_of(url: Optional[str]) -> Optional[str]:
    if not url:
        return None
    netloc = urllib.parse.urlsplit(url).netloc
    return netloc[4:] if netloc.startswith("www.") else (netloc or None)


def normalise(record: Dict[str, Any], index: int, source: Optional[str] = None) -> Dict[str, Any]:
    """Coerce one record into the canonical schema, leaving unknowns as None."""
    out: Dict[str, Any] = {key: _pick(record, key) for key in FIELDS}

    out["url"] = normalise_url(out["url"])
    out["year"] = int(_num(out["year"]) or 0) or None
    out["price"] = _num(out["price"])
    out["miles"] = _num(out["miles"])
    out["owners"] = int(_num(out["owners"]) or 0) or None
    out["distance"] = _num(out["distance"])
    out["daysOnMarket"] = _num(out["daysOnMarket"])
    out["mpg"] = _num(out["mpg"])
    out["make"] = _text(out["make"]).title() or None
    out["model"] = _text(out["model"]) or None
    out["vin"] = (_text(out["vin"]).upper() or None)
    if out["vin"] and not re.fullmatch(r"[A-HJ-NPR-Z0-9]{17}", out["vin"]):
        out["vin"] = None                       # a malformed VIN is worse than no VIN
    out["state"] = (_text(out["state"]).upper()[:2] or None)
    out["source"] = _text(out["source"]) or host_of(out["url"]) or source
    out["seenAt"] = _text(out["seenAt"]) or date.today().isoformat()
    out["id"] = _text(out["id"]) or out["vin"] or f"L{index}"
    return out


def usable(listing: Dict[str, Any]) -> bool:
    """Enough to price and score: year, make, model, a price and an odometer reading."""
    return bool(
        listing.get("year") and listing.get("make") and listing.get("model")
        and listing.get("price") and listing["price"] > 100
        and listing.get("miles") is not None and listing["miles"] >= 0
    )


def fingerprint(listing: Dict[str, Any]) -> str:
    if listing.get("vin"):
        return listing["vin"]
    # Failing a VIN: a named dealer plus model-year and mileage identifies a car well
    # enough that price is deliberately left out — the same car listed at two prices is
    # exactly the duplicate worth catching. With no dealer, price is the discriminator.
    base = [
        str(listing.get("year")), _text(listing.get("make")).lower(),
        _text(listing.get("model")).lower(),
        str(int((listing.get("miles") or 0) // 500)),
    ]
    dealer = _text(listing.get("dealer")).lower()
    if dealer:
        return "|".join(base + [dealer])
    return "|".join(base + [str(int((listing.get("price") or 0) // 250)),
                            _text(listing.get("seller")).lower()])


def dedupe(listings: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Keep the cheapest sighting of each car; note the others as duplicates."""
    kept: Dict[str, Dict[str, Any]] = {}
    order: List[str] = []
    for listing in listings:
        key = fingerprint(listing)
        if key not in kept:
            listing.setdefault("duplicates", [])
            kept[key] = listing
            order.append(key)
            continue
        current = kept[key]
        loser = listing
        if (listing.get("price") or 0) < (current.get("price") or 0):
            listing["duplicates"] = current.get("duplicates", [])
            kept[key] = listing
            loser = current
        kept[key].setdefault("duplicates", []).append({
            "price": loser.get("price"), "source": loser.get("source"), "url": loser.get("url"),
        })
    return [kept[k] for k in order]


# ------------------------------------------------------------------- fetching


_robots_cache: Dict[str, urllib.robotparser.RobotFileParser] = {}


def robots_allows(url: str) -> bool:
    """Check robots.txt for this host, caching one parser per origin."""
    parts = urllib.parse.urlsplit(url)
    origin = f"{parts.scheme}://{parts.netloc}"
    parser = _robots_cache.get(origin)
    if parser is None:
        parser = urllib.robotparser.RobotFileParser()
        parser.set_url(urllib.parse.urljoin(origin, "/robots.txt"))
        try:
            parser.read()
        except Exception as exc:  # noqa: BLE001 - unreachable robots.txt is not fatal
            logger.warning("Could not read robots.txt for %s (%s); treating as disallowed",
                           origin, type(exc).__name__)
            parser = None
            _robots_cache[origin] = None  # type: ignore[assignment]
            return False
        _robots_cache[origin] = parser
    if parser is None:
        return False
    return parser.can_fetch(USER_AGENT, url)


def fetch_page(url: str, timeout: int = 30) -> str:
    if not robots_allows(url):
        raise FetchError(f"robots.txt disallows fetching {url}")
    request = urllib.request.Request(url, headers={
        "User-Agent": USER_AGENT,
        "Accept": "text/html,application/xhtml+xml",
    })
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            charset = response.headers.get_content_charset() or "utf-8"
            return response.read().decode(charset, errors="replace")
    except (urllib.error.URLError, urllib.error.HTTPError, OSError) as exc:
        raise FetchError(f"{url}: {exc}") from exc


JSONLD_RE = re.compile(
    r'<script[^>]+type=["\']application/ld\+json["\'][^>]*>(.*?)</script>',
    re.DOTALL | re.IGNORECASE,
)


def _walk_jsonld(node: Any) -> Iterable[Dict[str, Any]]:
    """Yield every dict in a JSON-LD tree, including @graph members."""
    if isinstance(node, list):
        for item in node:
            yield from _walk_jsonld(item)
    elif isinstance(node, dict):
        yield node
        for key in ("@graph", "itemListElement", "item", "mainEntity", "offers"):
            if key in node:
                yield from _walk_jsonld(node[key])


def extract_jsonld_vehicles(html: str, url: Optional[str] = None) -> List[Dict[str, Any]]:
    """Pull schema.org Vehicle/Car records out of a page's JSON-LD.

    Listing sites publish this markup so search engines can read their inventory, which
    makes it the most stable and most appropriate thing to parse.
    """
    found: List[Dict[str, Any]] = []
    for block in JSONLD_RE.findall(html):
        try:
            parsed = json.loads(block.strip())
        except json.JSONDecodeError:
            continue
        for node in _walk_jsonld(parsed):
            types = node.get("@type")
            types = [types] if isinstance(types, str) else (types or [])
            if not any(t in ("Vehicle", "Car", "Motorcycle", "Product") for t in types):
                continue

            offers = node.get("offers") or {}
            if isinstance(offers, list):
                offers = offers[0] if offers else {}
            odometer = node.get("mileageFromOdometer") or {}
            if isinstance(odometer, dict):
                odometer = odometer.get("value")
            brand = node.get("brand") or node.get("manufacturer") or {}
            if isinstance(brand, dict):
                brand = brand.get("name")

            record = {
                "vin": node.get("vehicleIdentificationNumber"),
                "year": node.get("vehicleModelDate") or node.get("modelDate")
                        or node.get("productionDate"),
                "make": brand,
                "model": node.get("model") if isinstance(node.get("model"), str) else None,
                "trim": node.get("vehicleConfiguration") or node.get("trim"),
                "miles": odometer,
                "price": offers.get("price") if isinstance(offers, dict) else None,
                "url": (offers.get("url") if isinstance(offers, dict) else None) or url,
                "source": urllib.parse.urlsplit(url).netloc if url else None,
                "notes": node.get("name"),
            }
            if record["year"]:
                match = re.search(r"\d{4}", str(record["year"]))
                record["year"] = match.group(0) if match else None
            # A name like "2019 Toyota Camry SE" often carries what the fields omit.
            if (not record["make"] or not record["model"]) and record["notes"]:
                match = re.match(r"\s*(\d{4})\s+(\S+)\s+(.+)", str(record["notes"]))
                if match:
                    record["year"] = record["year"] or match.group(1)
                    record["make"] = record["make"] or match.group(2)
                    record["model"] = record["model"] or match.group(3)
            if record["price"] or record["vin"]:
                found.append(record)
    return found


def fetch_listings(urls: Sequence[str], delay: float = REQUEST_DELAY_SECONDS) -> List[Dict[str, Any]]:
    """Fetch each URL politely and extract whatever structured vehicles it declares."""
    collected: List[Dict[str, Any]] = []
    for index, url in enumerate(urls):
        if index:
            time.sleep(delay)
        try:
            html = fetch_page(url)
        except FetchError as exc:
            logger.warning("Skipped: %s", exc)
            continue
        vehicles = extract_jsonld_vehicles(html, url)
        if not vehicles:
            logger.warning("No structured vehicle data found at %s — "
                           "the page may render its listings with JavaScript. "
                           "Have an assistant read it and emit JSON instead (see AGENTS.md).", url)
        collected.extend(vehicles)
        logger.info("%s -> %d listing(s)", url, len(vehicles))
    return collected


# -------------------------------------------------------------------- output


def load_existing(path: str) -> List[Dict[str, Any]]:
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
        return payload.get("listings", []) if isinstance(payload, dict) else list(payload)
    except (OSError, ValueError) as exc:
        logger.warning("Could not read %s (%s); starting fresh", path, exc)
        return []


def write_database(listings: List[Dict[str, Any]], query: Optional[str],
                   js_path: str, json_path: str) -> Dict[str, Any]:
    sources = sorted({l["source"] for l in listings if l.get("source")})
    payload = {
        "schema": SCHEMA_VERSION,
        "generated": datetime.now().replace(microsecond=0).isoformat(),
        "query": query,
        "sources": sources,
        "count": len(listings),
        "listings": listings,
    }
    body = json.dumps(payload, indent=1, ensure_ascii=False)

    with open(json_path, "w", encoding="utf-8") as handle:
        handle.write(body + "\n")

    with open(js_path, "w", encoding="utf-8") as handle:
        handle.write(JS_HEADER)
        handle.write("(function (root) {\n  var data = ")
        handle.write(body.replace("\n", "\n  "))
        handle.write(";\n  if (typeof module === 'object' && module.exports) module.exports = data;\n")
        handle.write("  else root.UCDA_LISTINGS = data;\n}(typeof self !== 'undefined' ? self : this));\n")
    return payload


def summarise(listings: Sequence[Dict[str, Any]]) -> str:
    if not listings:
        return "No listings."
    prices = sorted(l["price"] for l in listings if l.get("price"))
    years = sorted(l["year"] for l in listings if l.get("year"))
    models: Dict[str, int] = {}
    for l in listings:
        key = f"{l.get('make')} {l.get('model')}"
        models[key] = models.get(key, 0) + 1
    top = sorted(models.items(), key=lambda kv: -kv[1])[:6]
    median_price = prices[len(prices) // 2] if prices else 0
    lines = [
        f"{len(listings)} listings",
        f"  price     ${prices[0]:,.0f} – ${prices[-1]:,.0f}  (median ${median_price:,.0f})" if prices else "",
        f"  years     {years[0]} – {years[-1]}" if years else "",
        f"  with VIN  {sum(1 for l in listings if l.get('vin'))}",
        "  models    " + ", ".join(f"{name} ({n})" for name, n in top),
    ]
    return "\n".join(line for line in lines if line)


# ----------------------------------------------------------------------- CLI


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    source = parser.add_argument_group("where the listings come from")
    source.add_argument("--from-json", metavar="PATH",
                        help="a file of listings: JSON, JSON in a markdown fence, one object "
                             "per line, or a delimited table — all accepted")
    source.add_argument("--from-csv", metavar="PATH", help="a CSV or TSV with a header row")
    source.add_argument("--stdin", action="store_true",
                        help="read listings from standard input, in any accepted form")
    source.add_argument("--fetch", nargs="+", metavar="URL",
                        help="fetch pages and extract schema.org vehicle data (robots-aware)")

    parser.add_argument("--merge", action="store_true",
                        help="add to the existing database instead of replacing it")
    parser.add_argument("--query", help="a note describing what this search was for")
    parser.add_argument("--out", default=DEFAULT_JS, help="output JS path")
    parser.add_argument("--out-json", default=DEFAULT_JSON, help="output JSON path")
    parser.add_argument("--delay", type=float, default=REQUEST_DELAY_SECONDS,
                        help="seconds between fetches (default 2)")
    parser.add_argument("--stats", action="store_true", help="summarise the database and exit")
    parser.add_argument("--schema", action="store_true", help="print the listing schema and exit")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO,
                        format="%(levelname)s %(message)s")

    if args.schema:
        print("Listing schema — every field optional except year, make, model, price, miles:\n")
        for field in FIELDS:
            print(f"  {field}")
        print("\nExample:\n")
        print(json.dumps({"listings": [{
            "year": 2019, "make": "Toyota", "model": "Camry", "trim": "SE",
            "miles": 52341, "price": 18995, "vin": "4T1B11HK5KU123456",
            "title": "clean", "accidents": "none", "owners": 1,
            "seller": "dealer", "dealer": "Example Motors", "city": "Vienna", "state": "VA",
            "distance": 12, "daysOnMarket": 34, "url": "https://example.com/l/1",
            "source": "example.com",
        }]}, indent=2))
        return 0

    if args.stats:
        existing = load_existing(args.out_json)
        print(summarise(existing))
        return 0

    raw: List[Dict[str, Any]] = []
    if args.from_json:
        with open(args.from_json, "r", encoding="utf-8", errors="replace") as handle:
            raw += parse_text(handle.read())
    if args.stdin:
        raw += parse_text(sys.stdin.read())
    if args.from_csv:
        with open(args.from_csv, "r", encoding="utf-8", errors="replace") as handle:
            raw += parse_text(handle.read())
    if args.fetch:
        raw += fetch_listings(args.fetch, delay=args.delay)

    if not raw:
        parser.print_help()
        print("\nNothing to ingest. Pick one of --from-json, --from-csv, --stdin or --fetch.")
        return 1

    normalised = [normalise(record, i) for i, record in enumerate(raw)]
    good = [l for l in normalised if usable(l)]
    rejected = len(normalised) - len(good)

    if args.merge:
        good = load_existing(args.out_json) + good

    deduped = dedupe(good)
    payload = write_database(deduped, args.query, args.out, args.out_json)

    print(summarise(deduped))
    if rejected:
        print(f"  skipped   {rejected} record(s) missing a year, make, model, price or odometer")
    removed = len(good) - len(deduped)
    if removed:
        print(f"  merged    {removed} duplicate sighting(s) of the same car")
    print(f"\nWrote {args.out} and {args.out_json} ({payload['count']} listings).")
    print("Open index.html and go to the Market section to rank them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
