"""The skeleton must be informed by real syllabi, not invented from scratch.

THE WEAKNESS
------------
Course skeletons were generated by the LLM alone — "give me modules for X" —
and nothing checked the result against how the subject is actually taught. The
measured consequence was a Pythagorean-theorem course covering 42% of its own
subject (no triples, no distance formula, no converse) that passed every
structural detector we run, because it WAS structurally clean. It was just
missing more than half the material.

An LLM asked to enumerate a syllabus produces what it can recall of one. A
textbook's chapter list IS a syllabus. Supplying it turns the model from an
author of imagined structure into an editor of real structure.

These test the pure logic. Network-dependent behaviour is exercised separately.
"""

import os
import sys
import unittest
from unittest import mock
from unittest.mock import patch

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
for p in (_ROOT, os.path.join(_ROOT, 'services/research')):
    if p not in sys.path:
        sys.path.insert(0, p)

import syllabus_sources as ss  # noqa: E402


class TestChapterFiltering(unittest.TestCase):
    """Front and back matter must not become course content."""

    def test_keeps_real_subject_chapters(self):
        for t in ("Right Triangles and Pythagorean Theorem", "Coordinate Systems",
                  "Area", "Cell division", "Endoplasmic Reticulum"):
            self.assertTrue(ss._is_content_chapter(t), t)

    def test_drops_apparatus(self):
        for t in ("Glossary", "Bibliography", "Authors", "Acknowledgements",
                  "Index", "Print version", "References", "Cover", "Meta"):
            self.assertFalse(ss._is_content_chapter(t), t)

    def test_drops_numbered_appendices(self):
        """OBSERVED LEAK: an exact-match set caught "Appendix" but not
        "Appendix A", "Appendix B", "Appendix C" — all three shipped into the
        evidence block for Geometry."""
        for t in ("Appendix", "Appendix A", "Appendix B", "Appendix C"):
            self.assertFalse(ss._is_content_chapter(t), t)

    def test_drops_numbering_artefacts(self):
        """OBSERVED LEAK: "Chapter 1 - HS" is a numbering artefact, not a
        topic, and the bare-number pattern did not match it."""
        for t in ("Chapter 1 - HS", "Chapter 12", "Part 3", "Unit 2", "4."):
            self.assertFalse(ss._is_content_chapter(t), t)

    def test_drops_contentless_openers(self):
        for t in ("Introduction", "Motivation"):
            self.assertFalse(ss._is_content_chapter(t), t)

    def test_drops_answer_keys(self):
        for t in ("Solutions", "Answers to exercises"):
            self.assertFalse(ss._is_content_chapter(t), t)


class TestOutlineShape(unittest.TestCase):

    def test_a_stub_book_is_not_used(self):
        """A two-chapter book would narrow the course to whatever those two
        happen to be — worse than not using it at all."""
        with patch.object(ss, '_search_book', return_value=['Tiny Book']), \
             patch.object(ss, '_chapters_of', return_value=['A', 'B']), \
             patch.object(ss, '_wikipedia_sections', return_value=[]):
            out = ss.subject_outline('x', min_chapters=4)
        self.assertFalse(out['found'])

    def test_a_real_book_is_used(self):
        with patch.object(ss, '_search_book', return_value=['Geometry']), \
             patch.object(ss, '_chapters_of',
                          return_value=['Angles', 'Area', 'Proof', 'Polygons', 'Similar Triangles']), \
             patch.object(ss, '_wikipedia_sections', return_value=[]):
            out = ss.subject_outline('geometry')
        self.assertTrue(out['found'])
        self.assertIn('Angles', out['outlines'][0]['chapters'])

    def test_broader_subjects_are_searched_too(self):
        """THE 42% CASE. "the pythagorean theorem" matches no Wikibook of its
        own, so without broadening there is no evidence at all and generation
        falls back to exactly the unguided behaviour that caused the gap."""
        seen = []

        def fake_search(api, query, limit=3):
            seen.append(query)
            return ['Geometry'] if query == 'Geometry' else []

        with patch.object(ss, '_search_book', side_effect=fake_search), \
             patch.object(ss, '_chapters_of',
                          return_value=['Angles', 'Area', 'Proof', 'Right Triangles']), \
             patch.object(ss, '_wikipedia_sections', return_value=[]):
            out = ss.subject_outline('the pythagorean theorem',
                                     broader_subjects=['Geometry'])
        self.assertIn('Geometry', seen)
        self.assertTrue(out['found'])

    def test_never_raises_when_everything_fails(self):
        with patch.object(ss, '_get_json', return_value=None):
            out = ss.subject_outline('anything')
        self.assertFalse(out['found'])
        self.assertEqual(out['outlines'], [])


class TestPromptFraming(unittest.TestCase):

    def _block(self):
        outline = {
            'topic': 'geometry', 'found': True, 'vocabulary': [],
            'outlines': [{'source': 'Wikibooks', 'book': 'Geometry',
                          'url': 'u', 'chapters': ['Angles', 'Area']}],
        }
        return ss.format_for_prompt(outline)

    def test_empty_when_nothing_found(self):
        self.assertEqual(ss.format_for_prompt({'found': False}), '')

    def test_names_the_book_so_the_evidence_is_attributable(self):
        self.assertIn('Geometry', self._block())
        self.assertIn('Wikibooks', self._block())

    def test_presented_as_real_syllabi(self):
        self.assertIn('real syllabi', self._block())


class TestSkeletonUsesTheEvidence(unittest.TestCase):

    def test_builder_asks_for_the_evidence_before_prompting(self):
        import inspect
        from services.core.course_builder import SkeletonBuilder
        src = inspect.getsource(SkeletonBuilder)
        self.assertIn('_syllabus_evidence', src)
        body = src[src.index('_syllabus_evidence_block = self._syllabus_evidence'):]
        self.assertIn('prompt = (', body,
                      'the evidence must be fetched before the prompt is built')

    def test_the_model_is_told_to_synthesise_not_copy(self):
        """The framing moved into the research brief itself (Phase 1), so it
        travels with the evidence rather than living in the builder."""
        import os
        root = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
        src = open(os.path.join(
            root, 'services/research/curriculum_research.py')).read()
        self.assertIn('SYNTHESISE, DO NOT COPY', src)
        self.assertIn('not any one source', src)

    def test_unguided_generation_is_logged_as_degraded(self):
        """Falling back silently would hide exactly the condition that produced
        the 42% course."""
        import inspect
        from services.core.course_builder import SkeletonBuilder
        src = inspect.getsource(SkeletonBuilder._syllabus_evidence)
        self.assertIn('UNGUIDED', src)
        self.assertIn('SYLLABUS_EVIDENCE:NONE', src)


if __name__ == '__main__':
    unittest.main()


class TestOpenStaxSource(unittest.TestCase):
    """OpenStax books are edited to a named course, which is the artefact this
    module wants. Two things have to hold: the right book, and real chapters."""

    def test_subject_fit_gates_selection_not_merely_scores_it(self):
        """REGRESSION: scoring alone chose "Introduction to Anthropology" for
        the Pythagorean theorem — no topical overlap whatsoever, but
        "Introduction to..." matched the level marker and that made it positive.
        Level fit may ORDER books already about the subject; it must never
        QUALIFY one that is not. This is the "geography textbook for a maths
        class" complaint in its exact form."""
        catalogue = {"u1": "Introduction to Anthropology",
                     "u2": "Contemporary Mathematics"}
        with mock.patch.object(ss, "_openstax_release",
                               return_value=("/a", {"u1": "v", "u2": "v"})), \
             mock.patch.object(ss, "_openstax_catalogue", return_value=catalogue), \
             mock.patch.object(ss, "_openstax_chapters",
                               side_effect=lambda a, u, v, **k: [
                                   "Ch %d" % i for i in range(8)]):
            out = ss._openstax_outline("The Pythagorean Theorem",
                                       ["Geometry", "Mathematics"], mastery=2)
        assert out is not None and out["book"] == "Contemporary Mathematics"

    def test_no_overlapping_book_yields_nothing_rather_than_least_bad(self):
        with mock.patch.object(ss, "_openstax_release",
                               return_value=("/a", {"u1": "v"})), \
             mock.patch.object(ss, "_openstax_catalogue",
                               return_value={"u1": "Introduction to Anthropology"}):
            assert ss._openstax_outline("The Pythagorean Theorem",
                                        ["Geometry"], mastery=2) is None

    def test_retired_editions_are_not_used(self):
        """A withdrawn edition still answers; teaching from it is a quiet way to
        teach superseded material."""
        payload = {"archiveUrl": "/apps/archive/x",
                   "books": {"live": {"defaultVersion": "1"},
                             "old": {"defaultVersion": "2", "retired": True}}}
        with mock.patch.object(ss, "_get_json", return_value=payload):
            archive, books = ss._openstax_release()
        assert archive == "/apps/archive/x"
        assert "live" in books and "old" not in books

    # WHAT REPLACED THE ARCHIVE-PARSER TESTS, AND WHY.
    #
    # Two tests here used to exercise `_openstax_chapters` stripping
    # `os-number`/`os-text` markup and descending into Biology's "Unit 2. The
    # Cell" wrappers. That parser is gone: the JSON it parsed came from
    # `openstax.org/apps/archive/.../contents/...`, and OpenStax's robots.txt
    # disallows BOTH `/apps/archive` and `/contents` for the WILDCARD agent.
    # The tests described the old behaviour accurately; the old behaviour was
    # a violation on every call.
    #
    # The concern they encoded — a chapter list must not carry positional
    # numbering into concept titles — still holds, and is asserted against the
    # replacement source in
    # `tests/research/test_libretexts.py::test_chapters_for_strips_positional_numbers`.

    def test_openstax_chapters_makes_no_request_to_openstax(self):
        """The endpoint is disallowed. Nothing may reach it, ever."""
        called = []
        with mock.patch.object(ss, "_get_json",
                               side_effect=lambda *a, **k: called.append(a)):
            ss._openstax_chapters("/apps/archive/x", "uid", "1",
                                  title="Calculus Volume 1")
        assert called == [], "a request was made to the disallowed endpoint"

    def test_openstax_chapters_needs_a_title_to_look_up(self):
        """The book's NAME is the key now, not its uuid. Without one the
        lookup cannot be made, and it must return nothing rather than guess."""
        assert ss._openstax_chapters("/a", "u", "v") == []
        assert ss._openstax_chapters("/a", "u", "v", title=None) == []

    def test_openstax_chapters_reads_libretexts(self):
        import services.research.libretexts as lt
        with mock.patch.object(lt, "chapters_for",
                               return_value=["Whole Numbers",
                                             "The Language of Algebra"]):
            ch = ss._openstax_chapters("/a", "u", "v", title="Prealgebra")
        assert ch == ["Whole Numbers", "The Language of Algebra"]

    def test_openstax_chapters_survives_a_dead_lookup(self):
        """A source failure must cost the outline, not the build."""
        import services.research.libretexts as lt
        with mock.patch.object(lt, "chapters_for",
                               side_effect=OSError("network down")):
            assert ss._openstax_chapters("/a", "u", "v", title="X") == []

    def test_the_disallowed_request_shape_refuses_to_run(self):
        """Retained deliberately, so the next person who wants chapter data
        sees that the obvious endpoint was tried and is not permitted."""
        try:
            ss._openstax_chapters_DISALLOWED("/a", "u", "v")
        except RuntimeError as e:
            assert "robots.txt" in str(e)
        else:
            raise AssertionError("the disallowed shape did not refuse")
